import type { Metadata } from "next";
/* eslint-disable @next/next/no-img-element -- media host is runtime configured */
import Link from "next/link";
import { notFound } from "next/navigation";
import type { Showcase } from "@wedjan/shared";
import { DiscoveryHeader } from "../../search/search-experience";
import styles from "../../discovery.module.css";
const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:8080";const WEB=process.env.NEXT_PUBLIC_WEB_URL??"http://localhost:3000";
async function getShowcase(slug:string){const r=await fetch(`${API}/api/v1/showcases/${encodeURIComponent(slug)}`,{next:{revalidate:300}});if(r.status===404)return null;if(!r.ok)throw new Error("Showcase unavailable");return r.json() as Promise<Showcase>}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const item=await getShowcase((await params).slug);return item?{title:`${item.title} · Real event | wedjan`,description:item.descriptionMd?.slice(0,155)??`A real ${item.eventType.toLowerCase()} in ${item.city}.`,openGraph:{images:item.coverUrl?[{url:item.coverUrl}]:[]}}:{title:"Event not found | wedjan"}}
export default async function ShowcasePage({params}:{params:Promise<{slug:string}>}){const item=await getShowcase((await params).slug);if(!item)notFound();const jsonLd={"@context":"https://schema.org","@type":"Event",name:item.title,startDate:item.eventDate,location:{"@type":"Place",address:{"@type":"PostalAddress",addressLocality:item.city,addressCountry:item.country}},image:item.media.map(x=>x.url),organizer:{"@type":"Organization",name:item.ownerBusinessName,url:`${WEB}/v/${item.ownerVendorSlug}`}};return <div className={styles.page}><DiscoveryHeader/><main className={styles.shell}><section className={styles.detailHero}>{item.coverUrl&&<img src={item.coverUrl} alt=""/>}<div><span>{item.eventType.toLowerCase()} · {item.city}</span><h1>{item.title}</h1><p>Captured by <Link href={`/v/${item.ownerVendorSlug}`}>{item.ownerBusinessName}</Link></p></div></section>{item.descriptionMd&&<p className={styles.landingIntro}>{item.descriptionMd}</p>}<section className={styles.gallery}>{item.media.map(media=><img key={media.id} src={media.url} alt={media.caption??item.title}/>)}</section><section className={styles.credits}><h2>Book this team</h2><Link href={`/v/${item.ownerVendorSlug}`}><span><strong>{item.ownerBusinessName}</strong><br/>Showcase owner</span><b>View vendor →</b></Link>{item.vendorTags.map(tag=><Link href={`/v/${tag.vendorSlug}`} key={tag.id}><span><strong>{tag.businessName}</strong><br/>{tag.roleLabel}</span><b>View vendor →</b></Link>)}</section><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd).replace(/</g,"\\u003c")}}/></main></div>}
