"use client";
/* eslint-disable @next/next/no-img-element -- media host is runtime configured */
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import type { VendorSearchResponse } from "@wedjan/shared";
import { api } from "@/lib/api";
import styles from "../discovery.module.css";

export function SearchExperience(){
  const params=useSearchParams(); const router=useRouter();
  const [data,setData]=useState<VendorSearchResponse>(); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [compare,setCompare]=useState<string[]>([]);
  const key=params.toString();
  useEffect(()=>{let active=true;const query=Object.fromEntries(new URLSearchParams(key).entries());
    api.GET("/api/v1/search/vendors",{params:{query}}).then(({data,error})=>{if(!active)return;if(error)setError("Search is temporarily unavailable.");else setData(data);setLoading(false);});return()=>{active=false};},[key]);
  function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const values=new FormData(event.currentTarget);const next=new URLSearchParams();for(const [name,value] of values)if(String(value).trim())next.set(name,String(value).trim());router.push(`/search?${next}`);}
  function suggestion(type:string,value:string){const next=new URLSearchParams(params);if(type==="NEARBY_CITY")next.set("city",value);else if(type==="ADJACENT_CATEGORY")next.set("category",value);else if(type==="WIDEN_PRICE"){next.delete("price_min");next.delete("price_max");}else next.forEach((_,k)=>next.delete(k));router.push(`/search?${next}`);}
  async function addToShortlist(vendorId:string,packageId:string){let list=(await api.GET("/api/v1/discovery/shortlists")).data?.items[0];if(!list)list=(await api.POST("/api/v1/discovery/shortlists",{body:{name:"My event"}})).data;if(!list)return router.push(`/login?next=${encodeURIComponent(`/search?${key}`)}`);const result=await api.POST("/api/v1/discovery/shortlists/{shortlistId}/items",{params:{path:{shortlistId:list.id}},body:{vendorId,packageId}});if(result.error)return router.push(`/login?next=${encodeURIComponent(`/search?${key}`)}`);window.alert(`Added to ${list.name}`)}
  const total=data?.total??0; const selected=useMemo(()=>new Set(compare),[compare]);
  return <div className={styles.page}><DiscoveryHeader/><main className={styles.shell}><section className={styles.hero}><h1>Find the right team, with real prices.</h1><p>Search verified vendors, combine every filter, and compare transparent packages before you reach out.</p></section>
    <form className={styles.searchForm} onSubmit={submit}><input className={styles.input} name="q" defaultValue={params.get("q")??""} placeholder="Try “photographer”"/><input className={styles.input} name="category" defaultValue={params.get("category")??""} placeholder="Category slug"/><input className={styles.input} name="city" defaultValue={params.get("city")??""} placeholder="City"/><button className={styles.button}>Search</button></form>
    <div className={styles.layout}><form className={styles.filters} onSubmit={submit}><h2>Refine results</h2><label>Minimum price</label><input className={styles.input} name="price_min" type="number" defaultValue={params.get("price_min")??""}/><label>Maximum price</label><input className={styles.input} name="price_max" type="number" defaultValue={params.get("price_max")??""}/><label>Guests</label><input className={styles.input} name="guests" type="number" min="1" defaultValue={params.get("guests")??""}/><label>Booking mode</label><select className={styles.select} name="booking_mode" defaultValue={params.get("booking_mode")??""}><option value="">Any</option><option value="INSTANT">Instant</option><option value="REQUEST">Request</option></select><label>Sort</label><select className={styles.select} name="sort" defaultValue={params.get("sort")??"RELEVANCE"}><option value="RELEVANCE">Best match</option><option value="PRICE_ASC">Price: low to high</option><option value="PRICE_DESC">Price: high to low</option><option value="NEWEST">Newest</option></select><button className={styles.button}>Apply</button></form>
      <section><div className={styles.resultsHead}><h2>{loading?"Searching…":`${total} vendor${total===1?"":"s"}`}</h2><span>{data?.nextCursor?"More matches available":"All matches shown"}</span></div>{error&&<div className={styles.empty}>{error}</div>}{!loading&&data?.items.length===0&&<div className={styles.empty}><h3>No exact matches yet</h3><p>Try one of these server-computed relaxations.</p><div className={styles.suggestions}>{data.suggestions.map(s=><button key={`${s.type}-${s.value}`} onClick={()=>suggestion(s.type,s.value)}>{s.label}</button>)}</div></div>}
      <div className={styles.grid}>{data?.items.map(card=><article className={styles.card} key={card.vendorId}>{card.coverUrl?<img className={styles.cardImage} src={card.coverUrl} alt=""/>:<div className={`${styles.cardImage} ${styles.placeholder}`}>◇</div>}<div className={styles.cardBody}><h3><Link href={`/v/${card.slug}`}>{card.businessName}</Link></h3><p>{card.categories.join(" · ")} · {card.city}</p><strong className={styles.price}>{money(card.cheapestPackage.priceCents,card.cheapestPackage.currency)}</strong><div className={styles.chips}>{card.badges.map(b=><span className={styles.chip} key={b}>{label(b)}</span>)}<span className={styles.chip}>{label(card.cheapestPackage.bookingMode)}</span></div><div className={styles.cardActions}><Link href={`/v/${card.slug}`}>View</Link><button type="button" onClick={async()=>{const {error}=await api.POST("/api/v1/discovery/favorites",{body:{entityType:"VENDOR",entityId:card.vendorId}});if(error)router.push(`/login?next=${encodeURIComponent(`/search?${key}`)}`);}}>♡ Save</button><button type="button" onClick={()=>void addToShortlist(card.vendorId,card.cheapestPackage.id)}>+ List</button><button type="button" aria-pressed={selected.has(card.cheapestPackage.id)} onClick={()=>setCompare(old=>old.includes(card.cheapestPackage.id)?old.filter(id=>id!==card.cheapestPackage.id):old.length<4?[...old,card.cheapestPackage.id]:old)}>{selected.has(card.cheapestPackage.id)?"✓ Compare":"Compare"}</button></div></div></article>)}</div></section></div>
    {compare.length>0&&<div className={styles.compareBar}><span>{compare.length}/4 selected</span><Link className={styles.button} href={`/compare?packages=${compare.join(",")}`}>Compare packages</Link></div>}</main></div>;
}
export function DiscoveryHeader(){return <header className={styles.header}><Link className={styles.wordmark} href="/">wedjan</Link><nav className={styles.nav}><Link href="/search">Vendors</Link><Link href="/inspiration">Inspiration</Link><Link href="/login">Sign in</Link></nav></header>}
function money(cents:number,currency:string){return new Intl.NumberFormat("en",{style:"currency",currency,maximumFractionDigits:0}).format(cents/100)}function label(v:string){return v.toLowerCase().replaceAll("_"," ").replace(/^./,x=>x.toUpperCase())}
